### ISSUE TITLE
Load environment variables from dotenv file

### ISSUE THREAD

**Issue by vovimayhem** [thoughtbot/parity#120]
As an alternative to #106, it would be useful if parity could load variables from a `.env` file (if it exists).

The problem we have right now is that our `config/database.yml` will not contain any information about our development host, port, etc, because it's read out from the `DATABASE_URL` env variable (which is set up in our compose file, working the same way heroku does):

```yml
default: &default
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: public,partitioning

development:
  <<: *default
  database: my_app_development

test:
  <<: *default
  database: my_app_test

production:
  <<: *default
```

Not having these values on the `config/database.yml` file causes `pg_restore` to try to connect to the local postgres' unix socket - which in our case does not exist:

```
development restore-from production
dropdb: could not connect to database template1: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
pg_restore: connecting to database for restore
pg_restore: [archiver (db)] connection to database "my_app_development" failed: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

But we do map our host port 5432 to the postgres container port, so we can reach it at `localhost:5432`:
```
PGHOST=localhost PGUSER=postgres development restore-from production
...
pg_restore: connecting to database for restore (working like a charm)
```

We don't need parity to do anything special other than read variables such as `PGHOST` and `PGUSER` values from the dotenv file, so the `pg_restore` command connects to the intended development database.

This way, we could keep parity unaware about the details on how the app runs in the developer machine (docker? rocket? on the host? Virtualized? It won't matter!)
