### ISSUE TITLE
Can't parse `database.yml` with environment variables and ERB

### ISSUE THREAD

**Issue by tannakartikey** [thoughtbot/parity#125]
Hello,

I installed it with apt-get on Ubuntu 16.04

`development restore-from staging` gives me the following error:
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27247  100 27247    0     0   3109      0  0:00:08  0:00:08 --:--:--  7992
sh: 1: Syntax error: "&&" unexpected
sh: 1: cannot open %=: No such file
```

Is there any way I can debug it or check out logs to know what is the error exactly for?

I use rbenv. I tried it with Ruby 2.1.1p76, 2.2.2p95

**Comment by geoffharcourt** [comment]
@tannakartikey do you have your database defined with an ERB file and a dynamic value?

**Comment by tannakartikey** [comment]
@geoffharcourt sorry did not get you about ERB file.

I have used [Figaro](https://github.com/laserlemon/figaro/) for ENV variables. Variables are used in the config/database.yml. Please find it below:

```
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: db/production.sqlite3

development:
  adapter: postgresql
  host: 127.0.0.1
  database: <%= ENV["CURRENTS_DB_NAME"] %>
  username: <%= ENV["CURRENTS_PSQL_USERNAME"] %>
  password: <%= ENV["CURRENTS_PSQL_PASSWORD"] %>

test:
  adapter: postgresql
  host: 127.0.0.1
  database: <%= ENV["CURRENTS_DB_NAME"] %>
  username: <%= ENV["CURRENTS_PSQL_USERNAME"] %>
  password: <%= ENV["CURRENTS_PSQL_PASSWORD"] %>
```
