### ISSUE TITLE
Automated task to update homebrew formula

### ISSUE THREAD

**Issue by geoffharcourt** [thoughtbot/parity#27]
I haven't figured out what the best way to do this is, but we should be updating the homebrew and APT formulae whenever we publish a new release. 

The rake task already generates the packages, so we'd want to have a task at the least generate the SHA256 hashes and URLs to paste into the formula as the bare-bones version of this automation, ideally it would be idiot-proof and just update the formula, but that might involve traversing git repos across a development machine in an unsafe way.

**Comment by ehershey** [comment]
I'm curious if there's a good way to do this, in general. I've been hunting for one and haven't found anything.

**Comment by croaky** [comment]
Maybe the API formulae should live in this repo rather than thoughtbot/formulae?

CI could be a good place for automating this.

Something like:

```yaml
before_deploy: bin/prepare-release
deploy:
  provider: releases
  api-key: "123456"
  file_glob: true
  file:
  - _releases/*.tar.gz
  - _releases/*.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
```
