### ISSUE TITLE
Replace `Parity.config` with `.parity.yml`?

### ISSUE THREAD

**Issue by croaky** [thoughtbot/parity#42]
With the change to a binary, configuring through Ruby no longer makes sense.

I'm thinking project-specific YAML files instead.

```yaml
database: "config/database.yml"
production: "my-heroku-app-production"
staging: "my-heroku-app-staging"
extra_environments:
- "feature-geoff"
- "qa"
redis_env: "REDIS_URL"
```

Thoughts?
